parameters:
    app.domain.project.project.class:                             AppBundle\Domain\Project\Project
    app.domain.user.user.class:                                   AppBundle\Domain\User\User

services:
    app.domain.project:
        class:            "%app.domain.project.project.class%"
        arguments:
            - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Project')"

    app.domain.user:
        class:            "%app.domain.user.user.class%"
        arguments:
            - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:User')"
            - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:VoteSettings')"
            - "@app.mail.sender"