parameters:
#    app.example.class: AppBundle\Example

services:
    app.security.bank_id:
        class: AppBundle\Security\BankIdService
        arguments:
            - %client_id%
            - %client_secret%
            - @router
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        arguments:
            - @app.security.bank_id
        tags:
            - { name: twig.extension }
    app.user_manager:
        class: AppBundle\Manager\UserManager
        arguments:
            - @logger
        calls:
            - [setDoctrine, [@doctrine]]
