AppBundle\Entity\Project:
    project{1..10}:
        title: <word(3)>
        description: <text(2000)>
        charge: <randomDigit()>
        owner: @user*
        source: <url()>
        approved: true
        city: ЧЕРКАСИ
        confirmedAt: <datetime()>
        confirmedBy: @admin*
        lastDateOfVotes: <datetime()>
