AppBundle\Entity\Project:
    project{1..10}:
        title: <word(3)>
        description: <text(2000)>
        owner: @user*
        source: <url()>
        confirm: <characterConfirm()>
        confirmedAt: <datetime()>
        confirmedBy: @admin*
