AppBundle\Entity\VoteSettings:
    voteSettings{1..2}:
        title: <word(3)>
        description: <text(2000)>
        dateFrom: <datetime()>
        dateTo: <datetime()>
        voteLimits: <randomNumber($nbDigits = 2)>
        location: @location*

AppBundle\Entity\Project:
    project{1..10}:
        title: <word(3)>
        description: <text(2000)>
        charge: <randomDigit()>
        owner: @user*
        source: <url()>
        approved: true
        city: ЧЕРКАСИ
        confirmedAt: <datetime()>
        confirmedBy: @admin*
        lastDateOfVotes: <dateTimeBetween("-10 days", "+200 days")>
        voteSetting: @voteSettings*