parameters:
    app.application.project.project.class:                             AppBundle\Application\Project\Project

services:
    app.application.project:
        class: "%app.application.project.project.class%"
        arguments:
            - "@app.domain.project"
            - "@app.domain.user"
            - "@security.token_storage"