parameters:
    app.repository.user.class:                                 AppBundle\Entity\UserRepository
    app.entity.user.class:                                     AppBundle\Entity\User

    app.repository.project.class:                              AppBundle\Entity\ProjectRepository
    app.entity.project.class:                                  AppBundle\Entity\Project

services:
    app.repository.user:
        class:            "%app.repository.user.class%"
        factory_service:  doctrine.orm.default_entity_manager
        factory_method:   getRepository
        arguments:
            - "%app.entity.user.class%"

    app.repository.project:
        class:            "%app.repository.project.class%"
        factory_service:  doctrine.orm.default_entity_manager
        factory_method:   getRepository
        arguments:
            - "%app.entity.project.class%"